version: "2"

services:
  mongo:
    container_name: mongo
    restart: unless-stopped
    hostname: db.mongo
    image: mongo
    volumes:
      - '../db:/data/db:consistent'
    ports:
      - "27017:27017"
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge